# Generated by Django 3.2.7 on 2021-10-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testMysql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testMysql', models.CharField(max_length=30, verbose_name='testMysql')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
